version: 2

report_sizes: true

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: pgcumber-build
    binary: pgcumber
    main: ./cmd/pgcumber
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"
    ldflags:
      - -s -w # Strip Symbol Table and Disable DWARF Generation for smaller binaries (default in goreleaser)
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

kos:
  - id: pgcumber-image
    build: pgcumber-build
    bare: true
    sbom: none
    working_dir: "."
    main: ./cmd/pgcumber
    repositories:
     -  arkadiusjonczek/pgcumber
    tags:
      - latest
      - "{{ .Tag }}{{ if index .Env \"IMAGE_TAG_SUFFIX\" }}{{ .Env.IMAGE_TAG_SUFFIX }}{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

homebrew_casks:
  - name: "{{ .ProjectName }}"
    homepage: "https://github.com/arkadiusjonczek/pgcumber"
    description: "Use Gherkin to write plain-text, human-readable test cases for your PostgreSQL data."
    repository:
      owner: arkadiusjonczek
      name: homebrew-pgcumber
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
